# coding: utf-8

# flake8: noqa

"""
    ORR Ont API Documentation

    The main ORR documentation is located at: http://mmisw.org/orrdoc/ ``` ###################################################### # NOTE #   OUT-OF-DATE for the time being. # Currently the swagger spec is maintained in the # https://github.com/mmisw/mmiorr-docs repo, which # is served at http://mmisw.org/orrdoc/api/ ###################################################### ``` __Note__: - We are in the process of writing this API documentation.   Please [let us know](https://github.com/mmisw/mmiorr-docs/issues) if you have any   questions or suggestions.  - Besides the documentation itself, this page also allows to directly exercise the API. - Actual requests from this page are against the endpoint at   `http://cor.esipfed.org/sparql`. This may change in a future version in   particular regarding a more general way of exercising the API (regardless   of concrete endpoint), or by allowing the selection of the particular endpoint.  - You can use the \"Authorize\" button above and enter your COR credentials to login   in this API interface. In this way you will be able to perform not only the basic   `GET` operations, but see expanded responses according to your access priviliges   and ontology visibility settings, as well as perform other operations as listed below.   # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import apis into sdk package
from swagger_client.api.ontology_api import OntologyApi
from swagger_client.api.organization_api import OrganizationApi
from swagger_client.api.user_api import UserApi

# import ApiClient
from swagger_client.api_client import ApiClient
from swagger_client.configuration import Configuration
# import models into sdk package
from swagger_client.models.ont import Ont
from swagger_client.models.org import Org
from swagger_client.models.possible_ontology_info import PossibleOntologyInfo
from swagger_client.models.post_ont import PostOnt
from swagger_client.models.post_org import PostOrg
from swagger_client.models.post_user import PostUser
from swagger_client.models.put_ont import PutOnt
from swagger_client.models.put_org import PutOrg
from swagger_client.models.put_user import PutUser
from swagger_client.models.uploaded_file_info import UploadedFileInfo
from swagger_client.models.user import User
