# coding: utf-8

"""
    ORR Ont API Documentation

    The main ORR documentation is located at: http://mmisw.org/orrdoc/ ``` ###################################################### # NOTE #   OUT-OF-DATE for the time being. # Currently the swagger spec is maintained in the # https://github.com/mmisw/mmiorr-docs repo, which # is served at http://mmisw.org/orrdoc/api/ ###################################################### ``` __Note__: - We are in the process of writing this API documentation.   Please [let us know](https://github.com/mmisw/mmiorr-docs/issues) if you have any   questions or suggestions.  - Besides the documentation itself, this page also allows to directly exercise the API. - Actual requests from this page are against the endpoint at   `http://cor.esipfed.org/sparql`. This may change in a future version in   particular regarding a more general way of exercising the API (regardless   of concrete endpoint), or by allowing the selection of the particular endpoint.  - You can use the \"Authorize\" button above and enter your COR credentials to login   in this API interface. In this way you will be able to perform not only the basic   `GET` operations, but see expanded responses according to your access priviliges   and ontology visibility settings, as well as perform other operations as listed below.   # noqa: E501

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six


class PostOrg(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'org_name': 'str',
        'members': 'list[str]',
        'url': 'str'
    }

    attribute_map = {
        'name': 'name',
        'org_name': 'orgName',
        'members': 'members',
        'url': 'url'
    }

    def __init__(self, name=None, org_name=None, members=None, url=None):  # noqa: E501
        """PostOrg - a model defined in Swagger"""  # noqa: E501

        self._name = None
        self._org_name = None
        self._members = None
        self._url = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if org_name is not None:
            self.org_name = org_name
        if members is not None:
            self.members = members
        if url is not None:
            self.url = url

    @property
    def name(self):
        """Gets the name of this PostOrg.  # noqa: E501


        :return: The name of this PostOrg.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this PostOrg.


        :param name: The name of this PostOrg.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def org_name(self):
        """Gets the org_name of this PostOrg.  # noqa: E501


        :return: The org_name of this PostOrg.  # noqa: E501
        :rtype: str
        """
        return self._org_name

    @org_name.setter
    def org_name(self, org_name):
        """Sets the org_name of this PostOrg.


        :param org_name: The org_name of this PostOrg.  # noqa: E501
        :type: str
        """

        self._org_name = org_name

    @property
    def members(self):
        """Gets the members of this PostOrg.  # noqa: E501

        Members of this organization  # noqa: E501

        :return: The members of this PostOrg.  # noqa: E501
        :rtype: list[str]
        """
        return self._members

    @members.setter
    def members(self, members):
        """Sets the members of this PostOrg.

        Members of this organization  # noqa: E501

        :param members: The members of this PostOrg.  # noqa: E501
        :type: list[str]
        """

        self._members = members

    @property
    def url(self):
        """Gets the url of this PostOrg.  # noqa: E501

        Website URL of the organization  # noqa: E501

        :return: The url of this PostOrg.  # noqa: E501
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """Sets the url of this PostOrg.

        Website URL of the organization  # noqa: E501

        :param url: The url of this PostOrg.  # noqa: E501
        :type: str
        """

        self._url = url

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(PostOrg, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PostOrg):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
